### ISSUE TITLE
Crashes when fuel from other mods is used in the generator.

### ISSUE THREAD

**Issue by Mitch12354** [kjmaster1/InventoryGenerators#15]
Minecraft Version: 1.14.4

Crashes when fuel from other mod is used in the generator. For example Aeternalis Fuel(basicly compressed coal) from projecte in overclocked generator)

Crash Report:
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 1/17/20 6:22 PM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at com.kjmaster.inventorygenerators.common.generators.ItemInvOverclockedGen.calculateTime(ItemInvOverclockedGen.java:31) ~[?:1.14.4-1.0.1] {re:classloading}
	at com.kjmaster.inventorygenerators.common.generators.ItemInventoryGenerator.func_77663_a(ItemInventoryGenerator.java:89) ~[?:1.14.4-1.0.1] {re:classloading}
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:405) ~[?:?] {re:classloading,xf:fml:quark:add-spacing-for-stack}
	at net.minecraft.entity.player.PlayerInventory.func_70429_k(PlayerInventory.java:265) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:492) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:attackspeedenchantment:PlayerEntity#getCooldownPeriod}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2032) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothpotiondmg}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:attackspeedenchantment:PlayerEntity#getCooldownPeriod}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:365) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:183) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:228) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.kjmaster.inventorygenerators.common.generators.ItemInvOverclockedGen.calculateTime(ItemInvOverclockedGen.java:31)
	at com.kjmaster.inventorygenerators.common.generators.ItemInventoryGenerator.func_77663_a(ItemInventoryGenerator.java:89)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:405)
	at net.minecraft.entity.player.PlayerInventory.func_70429_k(PlayerInventory.java:265)
	at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:492)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2032)
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:232)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.entity.player.ServerPlayerEntity)
	Entity ID: 288
	Entity Name: karrottheparrot2
	Entity's Exact location: 40.26, 64.00, -165.65
	Entity's Block location: World: (40,64,-166), Chunk: (at 8,4,10 in 2,-11; contains blocks 32,0,-176 to 47,255,-161), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:365)
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:183)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:228)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@9f0d367
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1033906880 bytes (986 MB) / 4033871872 bytes (3847 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx9216m -Xms256m -XX:PermSize=256m
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.111.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.111.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.111.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.111.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.111.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.111
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		followingvillagers-1.14.4-1.2.0.jar Following Villagers {followingvillagers@1.14.4-1.2.0 DONE}
		CyclopsCore-1.14.4-1.6.1.jar Cyclops Core {cyclopscore@1.6.1 DONE}
		aiotbotania-1.14.4-1.1.1.jar AIOT Botania {aiotbotania@1.14.4-1.1.1 DONE}
		ProjectE-1.14.4-PE1.0.1B.jar ProjectE {projecte@1.14.4-PE1.0.1B DONE}
		planttech2-0.01.06.jar PlantTech 2 {planttech2@0.01.06 DONE}
		SilentMechanisms-1.14.4-0.6.11+44.jar Silent's Mechanisms {silents_mechanisms@0.6.11+44 DONE}
		bambooeverything-1.14-1.5.0.jar Bamboo Everything {bambooeverything@1.14-1.5.0 DONE}
		modnametooltip_1.14.3-1.12.1.jar Mod Name Tooltip {modnametooltip@1.12.1 DONE}
		KleeSlabs_1.14.4-7.4.8.jar KleeSlabs {kleeslabs@7.4.8 DONE}
		IronJetpacks-1.14.4-2.0.3.jar Iron Jetpacks {ironjetpacks@2.0.3 DONE}
		xnet-1.14-1.8.7-alpha.jar XNet {xnet@1.14-1.8.7-alpha DONE}
		XaerosWorldMap_1.5.4_Forge_1.14.4.jar Xaero's World Map {xaeroworldmap@1.5.4 DONE}
		CookingForBlockheads_1.14.4-7.4.2.jar Cooking for Blockheads {cookingforblockheads@7.4.2 DONE}
		Controlling-5.0.5.jar Controlling {controlling@5.0.5 DONE}
		ReAuth-1.14-3.8.0.jar ReAuth {reauth@3.8.0 DONE}
		Placebo-1.14.4-2.3.5.jar Placebo {placebo@2.3.5 DONE}
		rangedpumps-0.6.1.jar Ranged Pumps {rangedpumps@0.6.1 DONE}
		potionsmaster-0.0.4-1.14.4-28.1.111.jar Potions Master {potionsmaster@0.0.4 DONE}
		Fence Jumper-1.14.4-1.0.8.jar FenceJumper {fencejumper@version DONE}
		Bookshelf-1.14.4-4.4.72.jar Bookshelf {bookshelf@4.4.72 DONE}
		u_team_core-1.14.4-2.8.0.140.jar U Team Core {uteamcore@2.8.0.140 DONE}
		randompatches-1.14.4-1.19.1.1.jar RandomPatches {randompatches@1.14.4-1.19.1.1 DONE}
		buildinggadgets-3.1.1b.jar Building Gadgets {buildinggadgets@3.1.1b DONE}
		DarkUtilities-1.14.4-2.0.10.jar Dark Utilities {darkutils@2.0.10 DONE}
		Apotheosis-1.14.4-2.4.4.jar Apotheosis {apotheosis@2.4.4 DONE}
		LightingWand-1.14.4-1.3.0.jar Lighting Wand {lightingwand@1.3.0 DONE}
		Morpheus-1.14.4-4.2.44.jar Morpheus {morpheus@version DONE}
		WaterStrainer-1.14.4-7.0.2.jar Water Strainer {waterstrainer@1.14.4-7.0.2 DONE}
		inventorygenerators-1.14.4-1.0.1.jar Inventory Generators {inventorygenerators@1.14.4-1.0.1 DONE}
		TMechworks-1.14.4-2.0.1.jar Tinkers' Mechworks {tmechworks@2.0.1 DONE}
		JustEnoughResources-1.14.4-0.10.0.70.jar Just Enough Resources {jeresources@0.10.0.70 DONE}
		BetterThanMending-1.3.2.jar BetterThanMending {betterthanmending@1.3.2 DONE}
		mysticallib-1.14.4-1.13.0.jar Mystical Lib {mysticallib@1.14.4-1.13.0 DONE}
		refinedstorage-1.7.3.jar Refined Storage {refinedstorage@1.7.3 DONE}
		industrial-foregoing-1.14.4-2.1.2-582ea8b.jar Industrial Foregoing {industrialforegoing@2.1.2 DONE}
		wetstone-1.1.2.jar Wetstone {wetstone@1.1.2 DONE}
		useful_backpacks-1.14.4-1.7.4.47.jar Useful Backpacks {usefulbackpacks@1.7.4.47 DONE}
		torchmaster-2.0.0-rc2.jar Torchmaster {torchmaster@2.0.0-rc2 DONE}
		BiomesOPlenty-1.14.4-9.0.0.262-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.259 DONE}
		valkyrielib-3.0.0.8.jar ValkyrieLib {valkyrielib@3.0.0.8 DONE}
		toughnessbar-4.1.jar Toughness Bar {toughnessbar@4.1 DONE}
		LLOverlayReloaded-1.2.4-mc1.14.4.jar Light Level Overlay Reloaded {llor@1.2.4-mc1.14.4 DONE}
		SolarFluxReborn-1.14.4-14.1.4.jar Solar Flux Reborn {solarflux@14.1.4 DONE}
		portality-1.14.4-2.0.4-b0b3467.jar Portality {portality@2.0.4 DONE}
		curios-FORGE-1.14.4-1.0.6.jar Curios API {curios@FORGE-1.14.4-1.0.6 DONE}
		Botania r1.11-375.jar Botania {botania@r1.11-375 DONE}
		Patchouli-1.1-24.jar Patchouli {patchouli@1.1-23 DONE}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 DONE}
		RandomThings-MC1.14.4-5.0.1.jar Random Things {randomthings@5.0.1 DONE}
		BetterThanLlamas-1.14.4-1.1.0.jar Better Than Llamas {betterthanllamas@1.1.0 DONE}
		OreExcavation-1.6.147.jar Ore Excavation {oreexcavation@NONE DONE}
		angelring-1.14.4-1.0.1.jar Angel Ring {angelring@1.0.1 DONE}
		lostcities-1.14-2.0.26-alpha.jar LostCities {lostcities@1.14-2.0.26-alpha DONE}
		elevatorid-1.14.4-1.5.2.jar Elevator Mod {elevatorid@1.14.4-1.5.2 DONE}
		tombstone-4.1.8-1.14.4.jar Corail Tombstone {tombstone@4.1.8 DONE}
		AttainedDrops-1.14.4-5.3.2.jar Attained Drops {attained_drops@5.3.2 DONE}
		cc-tweaked-1.14.4-1.86.2.jar CC: Tweaked {computercraft@1.86.2 DONE}
		AI-Improvements-1.14.4-0.3.0.jar AI-Improvements {aiimprovements@0.2.2 DONE}
		tramplestopper-1.14.4-2.0.0.26-universal.jar Trample Stopper {tramplestopper@1.14.4-2.0.0.26-universal DONE}
		YAMDA-4.1.1.jar YAMDA {yamda@4.1.1 DONE}
		StevesFactoryManager-1.14.4-3.0.0-alpha25.jar Steve's Factory Manager {sfm@1.14.4-3.0.0-alpha DONE}
		rockcandy-1.14.4-1.1.6.jar Rock Candy {rockcandy@version DONE}
		reallysimpletanks-1.01.jar Really Simple Tanks {reallysimpletanks@1.01 DONE}
		Cyclic-1.14.4-0.1.2.jar Cyclic {cyclic@1.14.4-0.1.2 DONE}
		attack_speed_enchantment-1.14.4-1.0.0.3.jar Attack Speed Enchantment {attackspeedenchantment@1.0.0.3 DONE}
		dwarfcoal-1.14.4-1.0.0.jar Dwarf Coal {dwarfcoal@1.14.3-1.1.0 DONE}
		inventorysorter-1.14.4-16.2.0.jar Simple Inventory Sorter {inventorysorter@16.2.0 DONE}
		Ma-Enchants-1.14.4-1.8.1.jar Ma Enchants {ma-enchants@1.14.4-1.8.1 DONE}
		Cucumber-1.14.4-2.0.6.jar Cucumber Library {cucumber@2.0.6 DONE}
		xray-1.14.4-2.0.2.jar Advanced XRay {xray@version DONE}
		BetterThanBunnies-1.14.4-1.2.0.jar Better Than Bunnies {betterthanbunnies@1.2.0 DONE}
		jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 DONE}
		metalbarrels-1.4.jar Metal Barrels {metalbarrels@1.4 DONE}
		Druidcraft-1.14-0.2.32.jar Druidcraft {druidcraft@0.2.32 DONE}
		AttributeFix-1.14.4-3.0.3.jar AttributeFix {attributefix@3.0.3 DONE}
		ensorcellation-1.14.4-0.2.0b.jar Ensorcellation {ensorcellation@0.2.0b DONE}
		Waystones_1.14.4-5.0.1.jar Waystones {waystones@5.0.1 DONE}
		enviromats-2.0.0.9.jar Environmental Materials {enviromats@2.0.0.9 DONE}
		comforts-FORGE-1.14.4-2.0-beta4.jar Comforts {comforts@FORGE-1.14.4-2.0-beta4 DONE}
		NaturesCompass-1.14.4-1.8.3.jar Nature's Compass {naturescompass@1.14.4-1.8.3 DONE}
		EnderBags-1.14.4-4.2.0.jar Ender Bags {ender_bags@4.2.0 DONE}
		SimpleStorageNetwork-1.14.4-0.2.0.jar Simple Storage Network {storagenetwork@1.14.4-0.2.0 DONE}
		angelblock-1.0a.jar Angel Block {angelblock@1.0a DONE}
		FarmingForBlockheads_1.14.4-5.3.1.jar Farming for Blockheads {farmingforblockheads@5.3.1 DONE}
		cofh_core-1.14.4-0.2.0b.jar CoFH Core {cofh_core@0.2.0b DONE}
		mcjtylib-1.14-3.5.17-alpha.jar McJtyLib {mcjtylib@1.14-3.5.17-alpha DONE}
		rftoolsbase-1.14-0.0.12-alpha.jar RFToolsBase {rftoolsbase@1.14-0.0.12-alpha DONE}
		rftoolsstorage-1.14-0.0.7-alpha.jar RFToolsStorage {rftoolsstorage@1.14-0.0.7-alpha DONE}
		restrictions-1.14-1.3.10.jar Restrictions {restrictions@1.14-1.3.10 DONE}
		ClickMachine-1.14.4-2.1.2.jar Click Machine {clickmachine@2.1.2 DONE}
		environmentalcreepers-forge-1.14.4-1.6.0.jar Environmental Creepers {environmentalcreepers@1.6.0 DONE}
		ToastControl-1.14.4-2.2.0.jar Toast Control {toastcontrol@2.2.0 DONE}
		PackingTape-1.14.4-0.9.2.jar Packing Tape {packingtape@0.9.2 DONE}
		mininggadgets-1.2.3.jar Mining Gadgets {mininggadgets@1.2.3 DONE}
		CraftTweaker-1.14.4-5.0.1.160.jar CraftTweaker {crafttweaker@5.0.1.160 DONE}
		rftoolspower-1.14-1.2.12-alpha.jar RFToolsPower {rftoolspower@1.14-1.2.12-alpha DONE}
		mysticalworld-1.14.4-1.7.1.jar Mystical World {mysticalworld@1.14.4-1.7.1 DONE}
		forge-1.14.4-28.1.111-universal.jar Forge {forge@28.1.111 DONE}
		PassthroughSigns-1.14.4-2.3.1.jar Passthrough Signs {passthroughsigns@1.14.4-2.3.1 DONE}
		QuickLeafDecay-MC1.14.4-1.2.5.jar Quick Leaf Decay {quickleafdecay@1.2.5 DONE}
		ColossalChests-1.14.4-1.7.6.jar ColossalChests {colossalchests@1.7.6 DONE}
		MysticalAgriculture-1.14.4-2.0.5.jar Mystical Agriculture {mysticalagriculture@2.0.5 DONE}
		ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 DONE}
		CraftingTweaks_1.14.4-10.1.5.jar Crafting Tweaks {craftingtweaks@10.1.5 DONE}
		forge-1.14.4-28.1.111-client.jar Minecraft {minecraft@1.14.4 DONE}
		rftoolsutility-1.14-1.2.14-alpha.jar RFToolsUtility {rftoolsutility@1.14-1.2.14-alpha DONE}
		Flopper-1.14.4-1.0.5.jar Flopper {flopper@1.0.5 DONE}
		theoneprobe-1.14-1.4.37.jar The One Probe {theoneprobe@NONE DONE}
		swingthroughgrass-1.14.4-1.3.2.jar SwingThroughGrass {swingthroughgrass@1.14.4-1.3.2 DONE}
		MouseTweaks-2.13-mc1.14.4.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		ToolBelt-1.14.4-1.12.5.jar Tool Belt {toolbelt@1.12.5 DONE}
		titanium-1.14.4-2.2.10.jar Titanium {titanium@2.2.10 DONE}
		SilentLib-1.14.4-4.4.0+44.jar Silent Lib {silentlib@4.4.0+44 DONE}
		bluepower-1.14.4-0.3.172-alpha-universal.jar Blue Power {bluepower@0.3.172-alpha DONE}
		forbidden_arcanus-1.14.4-1.5.jar Forbidden & Arcanus {forbidden_arcanus@1.14.4-1.5 DONE}
		archers_paradox-1.14.4-0.1.0a.jar Archer's Paradox {archers_paradox@0.1.0b DONE}
		Ding-1.14.4-1.1.0.jar Ding {ding@1.1.0 DONE}
		rftoolsbuilder-1.14-1.2.12-alpha.jar RFToolsBuilder {rftoolsbuilder@1.14-1.2.12-alpha DONE}
		Quark-r2.0-209.jar Quark {quark@r2.0-209 DONE}
		Mantle-1.14.4-1.4.32.jar Mantle {mantle@1.4.32 DONE}
		Xaeros_Minimap_1.19.6_Forge_1.14.4.jar Xaero's Minimap {xaerominimap@1.19.6 DONE}
		JAOPCA-1.14.4-3.0.0.14.jar JAOPCA {jaopca@3.0.0.14 DONE}
		FastWorkbench-1.14.4-2.1.4.jar FastWorkbench {fastbench@2.1.4 DONE}
		StorageDrawers-1.14.4-6.0.5.jar Storage Drawers {storagedrawers@1.14.4-6.0.3 DONE}
		chunkloader-1.14.4-1.0.0.jar Chunk Loader {chunkloader@1.14.4-1.0.0 DONE}
		Harvest-forge-1.14.4-1.2.10-23.jar Harvest {harvest@version DONE}
		Dirt2Path-1.0.0.jar Dirt2Path {d2p@1.0.0 DONE}
		dde_1.14.4-1.0.jar Dragon Drops Elytra {dde@1.0 DONE}
		FastFurnace-1.14.4-2.2.4.jar FastFurnace {fastfurnace@2.2.4 DONE}
		AppleSkin-mc1.14.4-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		RefinedRelocation_1.14.4-6.2.5.jar Refined Relocation {refinedrelocation@6.2.5 DONE}
		Aquaculture-1.14.4-2.0.3.jar Aquaculture 2 {aquaculture@1.14.4-2.0.3 DONE}
		XL-Food-Mod-1.14.4-2.2.1.jar XL Food Mod {xlfoodmod@2.2.1 DONE}
		refinedstorageaddons-0.5.jar Refined Storage Addons {refinedstorageaddons@0.5 DONE}
		Ma-Essentials-1.14.4-1.2.10.jar Ma Essentials {ma-essentials@1.14.4-1.2.10 DONE}
		CosmeticArmorReworked-1.14.4-v1a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.14.4-v1a DONE}
		overloadedarmorbar-3.0.0b.jar Overloaded Armor Bar {overloadedarmorbar@3.0.0b DONE}
		DefaultOptions_1.14.4-10.2.7.jar Default Options {defaultoptions@10.2.7 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['karrottheparrot2'/288, l='ATM5 Test', x=40.26, y=64.00, z=-165.65]]
	Data Packs: vanilla, inmemory:jaopca, mod:aiimprovements, mod:aiotbotania, mod:angelblock, mod:angelring, mod:apotheosis, mod:appleskin, mod:aquaculture, mod:archers_paradox, mod:arl, mod:attained_drops, mod:attributefix, mod:bambooeverything, mod:betterthanbunnies, mod:betterthanllamas, mod:betterthanmending, mod:biomesoplenty, mod:bluepower, mod:bookshelf, mod:botania, mod:buildinggadgets, mod:chunkloader, mod:clickmachine, mod:cofh_core, mod:colossalchests, mod:comforts, mod:computercraft, mod:controlling, mod:cookingforblockheads, mod:cosmeticarmorreworked, mod:craftingtweaks, mod:crafttweaker, mod:cucumber, mod:curios, mod:cyclic, mod:cyclopscore, mod:d2p, mod:darkutils, mod:defaultoptions, mod:ding, mod:druidcraft, mod:dwarfcoal, mod:elevatorid, mod:ender_bags, mod:ensorcellation, mod:enviromats, mod:environmentalcreepers, mod:farmingforblockheads, mod:fastbench, mod:fastfurnace, mod:fencejumper, mod:flopper, mod:followingvillagers (incompatible), mod:forbidden_arcanus, mod:forge, mod:harvest, mod:industrialforegoing (incompatible), mod:inventorysorter, mod:ironchest, mod:ironjetpacks, mod:jaopca, mod:jei, mod:jeresources (incompatible), mod:kleeslabs, mod:lightingwand, mod:llor, mod:lostcities, mod:ma-enchants, mod:ma-essentials, mod:mantle, mod:mcjtylib, mod:metalbarrels, mod:mininggadgets, mod:modnametooltip, mod:morpheus, mod:mousetweaks, mod:mysticalagriculture, mod:mysticallib, mod:mysticalworld, mod:naturescompass, mod:oreexcavation, mod:packingtape, mod:passthroughsigns (incompatible), mod:patchouli, mod:placebo, mod:planttech2 (incompatible), mod:portality (incompatible), mod:potionsmaster, mod:projecte, mod:quark, mod:quickleafdecay, mod:randompatches, mod:randomthings, mod:rangedpumps, mod:reallysimpletanks, mod:reauth, mod:refinedrelocation, mod:refinedstorage, mod:refinedstorageaddons, mod:restrictions, mod:rftoolsbase, mod:rftoolsbuilder, mod:rftoolspower, mod:rftoolsstorage, mod:rftoolsutility, mod:rockcandy, mod:sfm, mod:silentlib, mod:silents_mechanisms, mod:solarflux, mod:storagedrawers, mod:storagenetwork, mod:swingthroughgrass, mod:theoneprobe, mod:titanium (incompatible), mod:tmechworks, mod:toastcontrol, mod:tombstone, mod:toolbelt, mod:torchmaster, mod:tramplestopper, mod:usefulbackpacks, mod:uteamcore, mod:valkyrielib, mod:waterstrainer, mod:waystones, mod:wetstone, mod:xaerominimap, mod:xaeroworldmap, mod:xlfoodmod, mod:xnet, mod:xray, mod:yamda, file/bluepower, mod:dde, mod:attackspeedenchantment, mod:overloadedarmorbar, mod:toughnessbar, mod:inventorygenerators
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by dm8mydog** [comment]
same issue with just adding a stack of charcoal blocks in. ugh

**Comment by MrRedstoneA1** [comment]
Possibly a mod incompatibility. I found no issue with any fuel from other mods.
